removed dependencies on exp-config & exp-correlator, rewrote a bunch
BonnierNews/exp-logger pull request #1
Opened 2022-12-22 10:37 UTC by OriginalDecode

2022-12-22 12:06 UTC, norla approved these changes

2022-12-22 12:08 UTC, markusn requested changes

2022-12-22 12:08 UTC, markusn commented on readme.md
> +  severityLabels // add extra label mappings, [ {label: "oldKey", newLabel: "newKey"}]
det är väl snarare add/replace?

2022-12-22 12:08 UTC, markusn commented on index.js
> +function severity(label, severityLabels) {
anropas den här för varje loggmeddelande? i sådant fall borde datastrukturen bytas från en array till en map/object

2022-12-23 08:57 UTC, markusn approved these changes

2022-12-23 08:58 UTC, merged